config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root to: redirect('/surveys')

  resources :surveys do
    resources :survey_questions
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/question.rb
class Question < ApplicationRecord
  belongs_to :survey
end

app/models/survey.rb
class Survey < ApplicationRecord
  has_many :questions, dependent: :destroy
  accepts_nested_attributes_for :questions, allow_destroy: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/survey_questions_controller.rb
class SurveyQuestionsController < ApplicationController
  def index
    @questions = Question.where('survey_id = ?', params[:survey_id])
  end
  
  # def show
  #   @survey = Survey.find(params[:survey_id])
  #   @question = Question.find_by_id(params[:question_id])
  #   render :index
  # end

  def new
    @survey = Survey.find(params[:survey_id])
    @question = @survey.questions.new
  end
  
  def create
    @question = Question.new(survey_question_params)
    @question.survey_id = params[:survey_id]
    @question.save
    redirect_to survey_survey_questions_path
  end

  def edit
    @survey = Survey.find(params[:survey_id])
    @question = @survey.questions.find_by_id(params[:id])
  end
  
  def update
    @survey = Survey.find(params[:survey_id])
    @question = @survey.questions.find(params[:format])
    if @question.update(survey_question_params)
      redirect_to survey_survey_questions_path
    else
      render :edit
    end
  end
  
  
  
  def destroy
    @survey = Survey.find(params[:survey_id])
    @question = @survey.questions.find(params[:id])
    @question.destroy
    redirect_to survey_path(@survey)
  end
  
  private
  
  def survey_question_params
    params.require(:question).permit(:question_id, :survey_id, :question)
  end
end

app/controllers/surveys_controller.rb
class SurveysController < ApplicationController
  def index
    @surveys = Survey.all
  end
  
  def show
    @survey = Survey.find(params[:id])
    # @survey_questions = @survey.questions
  end

  def new
    @survey = Survey.new
  end

  def edit
    @survey = Survey.find(params[:id])
  end

  def create
    @survey = Survey.new(survey_params)
    if @survey.save
      redirect_to surveys_path
    else
      render 'new'
    end
  end
  
  def update
    @survey = Survey.find(params[:id])
    if @survey.update(survey_params)
      redirect_to @survey
    else
      render 'edit'
    end
  end
  
  def destroy
    @survey = Survey.find(params[:id])
    @survey.destroy
    
    redirect_to surveys_path
  end

  private

  def survey_params
    params.require(:survey).permit(:name, :summary, :date,
                                   questions_attributes: [:id, :question_id, :question, :_destroy])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/survey_questions_helper.rb
module SurveyQuestionsHelper
end

app/helpers/surveys_helper.rb
module SurveysHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Survey Project</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>

    <!--Import Google Icon Font-->
    <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
    <!-- Compiled and minified CSS -->
   <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0/css/materialize.min.css">
  </head>

  <body>
    <nav>
      <div class="nav-wrapper">
        <a href="/" class="brand-logo right">Survey Project</a>
        <ul id="nav-mobile" class="left hide-on-med-and-down">
          <li><%= link_to('Surveys', surveys_path) %></li>
        </ul>
      </div>
    </nav>

    <%= yield %>

    <!-- Compiled and minified JavaScript -->
    <script src="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0/js/materialize.min.js"></script>
  </body>
</html>

app/views/survey_questions/edit.html.erb
<div class="row">
  <div class="col s12 m6">
    <h4>Edit Survey Question</h4>

    <%= form_for [@survey, @survey, @question] do |questions_form| %>
      <p>
        <%= questions_form.label :question %>
        <%= questions_form.text_field :question %>
      </p>

      <p>
        <%= questions_form.submit %>
      </p>
    <% end %>

  </div>
</div>

app/views/survey_questions/index.html.erb
<div class="row">
  <div class="col s12 m6">
    <ul class="collection with-header">
      <li class="collection-header"><h4>Survey Questions</h4></li>
      <!-- list survey questions for this survey -->
      <% @questions.each do |question| %>
        <li class="collection-item">
          <%= question.question %>
          <%= link_to "Edit", edit_survey_survey_question_path(question.survey, question) %>

        </li>
      <% end %>
    </ul>

    <div class="row">
      <div class="col s12 m6">
        <%= link_to('Create Question',
                    new_survey_survey_question_path,
                    class: "btn waves-effect waves-light") %>
      </div>
    </div>
  </div>
</div>

app/views/survey_questions/new.html.erb
<style>
  select {
    display: block;}
</style>

<div class="row">
  <div class="col s12 m6">
    <h4>New Survey Question</h4>

    <%= form_for [@survey, @survey, Question.new] do |questions_form| %>
      <p>
        <%= questions_form.label :question %>
        <%= questions_form.text_field :question %>
      </p>

      <p>
        <%= questions_form.label "Question Type" %>
        <%= select_tag(:question_id, options_for_select([["First", 1], ["Second", 2], ["Third", 3]])) %>
      </p>

      <p>
        <%= questions_form.submit %>
      </p>

    <% end %>

  </div>
</div>

app/views/survey_questions/show.html.erb
<!--<div class="row">-->
<!--  <div class="col s12 m6">-->
<!--    <ul class="collection with-header">-->
<!--      <li class="collection-header"><h4>Survey Questions</h4></li>-->
<!--      <!-- list survey questions for this survey -->-->
      <%# @survey.questions.each do |question| %>
<!--        <li class="collection-item">-->
          <%#= question.question %>
          <%#= link_to "Edit", edit_survey_survey_question_path %>

          <%#= link_to "Delete", survey_survey_questions_path,
                      :data => {
                          :confirm => "Are you sure?",
                          :method => "delete"
                      } %>
<!--        </li>-->
      <%# end %>
<!--      <!--      <li class="collection-item">Survey Question 1</li>-->-->
<!--    </ul>-->

<!--    <div class="row">-->
<!--      <div class="col s12 m6">-->
<!--        <%#= link_to('Create Question',-->
<!--                    new_survey_survey_question_path,-->
                    class: "btn waves-effect waves-light") %>
<!--      </div>-->
<!--    </div>-->
<!--  </div>-->
<!--</div>-->

app/views/surveys/edit.html.erb
<div class="row">
  <div class="col s12 m6">
    <h4>Edit Survey</h4>

    <%= form_for @survey do |f| %>
      <p>
        <%= f.label :name %>
        <%= f.text_field :name %>
      </p>

      <p>
        <%= f.label :date %>
        <%= f.date_field :date, class: "form-control" %>
      </p>

      <%= f.submit %>
    <% end %>

  </div>
</div>

app/views/surveys/index.html.erb
<div class="row">
  <div class="col s12 m6">
    <ul class="collection with-header">
      <li class="collection-header"><h4>Surveys</h4></li>
      <!-- list surveys -->
      <% @surveys.each do |survey| %>
        <li class="collection-item">
          <%= link_to survey.name, survey_path(survey) %> <%= survey.date %>
        </li>
      <% end %>
    </ul>

    <div class="row">
      <div class="col s12 m6">
        <%= link_to('Create Survey',
                    new_survey_path,
                    class: "btn waves-effect waves-light") %>
      </div>
    </div>
  </div>
</div>

app/views/surveys/new.html.erb
<div class="row">
  <div class="col s12 m6">
    <h4>New Survey</h4>

    <%= form_for @survey do |f| %>
      <p>
        <%= f.label :name %>
        <%= f.text_field :name %>
      </p>

      <p>
        <%= f.label "due date" %>
        <%= f.date_field :date, class: "form-control" %>
      </p>

      <%= f.submit %>
    <% end %>

  </div>
</div>

app/views/surveys/show.html.erb
<div class="row">
  <div class="col s12 m6">
    <h1><%= @survey.name %></h1>

    <h6>Due Date: <%= @survey.date %></h6>

    <p>
      <%= link_to "View Questions", survey_survey_questions_path(@survey) %>
    </p>

<!--    <p>-->
      <%#= link_to "Add a Question", new_survey_survey_question_path(@survey) %>
<!--    </p>-->

    <p>
      <%= link_to "Edit Survey", edit_survey_path(@survey) %>
    </p>

    <p>
      <%= link_to "Delete Survey", survey_path(@survey),
                  method: :delete,
                  data: { confirm: 'Are you sure?' } %>
    </p>

    <p>
      <%= link_to "Return to Surveys Home", surveys_path %>
    </p>
  </div>
</div>